Header feature
RaviTejaM9602/Portfolio pull request #4
Opened 2021-11-25 13:41 UTC by RaviTejaM9602

This is a duplicate of Figma mobile template one, header section

2021-11-25 16:20 UTC, andersonlebon requested changes
Hi @RaviTejaM9602 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub flow :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ]  The Repository should have a descriptive Pull Request message and a Pull Request meaningful title, this is important because we let the reviewer or any other user the intent of the changes we are about to merge with a production branch.
- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 22:01 UTC, RaviTejaM9602 commented
Pull request
Ravi Teja M
What does this PR do?
This PR is the continuation of the skeleton of a portfolio page. (mobile version)
Update Logo and Nav Bar as per above review comments 
Added the section, ul, li, tags in the HTML file
Used CSS file to style up the tags in HTML file
created test.MD files that have been ignored
How should it be tested
clone the repository
git clone https://github.com/RaviTejaM9602/Portfolio.git

2021-11-26 02:41 UTC, andersonlebon requested changes
Hi @RaviTejaM9602 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 02:41 UTC, andersonlebon commented on index.html
> +      </nav>
- [ ] Good job on implementing the previous request. However, you still have something to improve:
- Kindly put this `<nav>` tag inside a `<header>` tag.

2021-11-26 02:41 UTC, andersonlebon commented on index.html
> +      <h2 class="intro">I'm Ravi Teja<span>glad to see</span><span>
- [ ] As I sad before the the main title(your name) should be a` <h1>` and not a `<h2>` tag. use this
```
<h1 class="intro">I'm Ravi Teja<span>glad to see</span><span>
 you!!</span></h1>
```

2021-11-26 02:41 UTC, andersonlebon commented on index.html
> +   </main>
- [ ] GOOD JOB :clap: :clap: I can see you have improved your styling you are almost there. you just have only to set the `font-family` as well as the `font-size`. Kindly follow the template style

| your design | the template|
| --------------- | ---------------- |
![Screenshot from 2021-11-26 04-38-02](https://user-images.githubusercontent.com/65068771/143518413-f13487e6-734c-4cf3-add6-5ba93c13b064.png) | ![143390039-f6c2a839-f2f9-4217-acae-05cf29dcefb2](https://user-images.githubusercontent.com/65068771/143435936-2c7eb81c-13b2-43c2-b449-77ae83affe45.png)

2021-11-26 16:01 UTC, RaviTejaM9602 commented
I have made required changes as mentioned above please find the screen shot for reference.

![portfolio](https://user-images.githubusercontent.com/72485137/143606722-6131bd59-3c63-469d-9e0e-88d6906b6119.PNG)

2021-11-26 16:13 UTC, andersonlebon commented
- [ ] OOh CONGRATULATIONS :clap:  i can see you improved your design kindly change `Marian` to your name and you will be ok

2021-11-26 16:37 UTC, RaviTejaM9602 commented
Done with the suggested Change 
![Capture](https://user-images.githubusercontent.com/72485137/143610521-c4d1e139-360a-424c-a5d7-84fb39093a7d.PNG)

2021-11-26 17:02 UTC, andersonlebon approved these changes
Hi @RaviTejaM9602 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 
- Your design is now looking good :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-30 15:52 UTC, merged